app:
  host: localhost
  port: 8080
  environment: development
timeouts:
  api_read_timeout: 60
  api_write_timeout: 60
database:
    username: postgres
    password: postgres
    name: scrummy-2
    port: 5432
cors:
  enabled: true
  allowed_headers:
    - X-Authorization-Timestamp
    - Accept
    - Authorization
    - Content-Type
    - X-Authorization-Content-SHA256
    - X-Request-ID
  allowed_methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
  allow_all_origins: true
debug:
  level: trace
  sql_queries: false

